package control_pagos;

import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import operaciones.funciones;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import operaciones.conexion;

public class confirmarPago extends javax.swing.JDialog {

    private SimpleDateFormat formato;
    private funciones fun;
    private static String usuario = "", ciclo;
    private float transporte = 0, colegiatura = 0;
    private boolean bandera = false, estado = false;

    public confirmarPago(java.awt.Frame parent, boolean modal, String usu, String ciclo) {
        super(parent, modal);
        initComponents();
        this.setTitle("Confirmación de pago ");
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/logo.png")).getImage());
        this.usuario = usu;
        this.ciclo = ciclo;
        fun = new funciones();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelNivel = new javax.swing.JLabel();
        labelGrado = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelTutor = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelPago = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelMes = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        labelTrans = new javax.swing.JLabel();
        labelBeca = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelRecargo = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labelTipoPago = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(86, 7, 12));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONFIRMAR PAGO");

        labelFecha.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        labelNombre.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelNombre.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel5.setText("Nivel:");

        labelNivel.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelNivel.setText("jLabel4");

        labelGrado.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelGrado.setText("jLabel4");

        jLabel8.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel8.setText("Grado:");

        labelTutor.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelTutor.setText("jLabel4");

        jLabel10.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel10.setText("Tutor:");

        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel11.setText("Teléfono:");

        labelTelefono.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelTelefono.setText("jLabel4");

        jLabel13.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel13.setText("Abono colegiatura:");

        labelPago.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelPago.setText("jLabel4");

        jLabel15.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel15.setText("Correspondiente a:");

        labelMes.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelMes.setText("jLabel4");

        jLabel17.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel17.setText("Recibió:");

        labelUsuario.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelUsuario.setText("jLabel4");

        btnGuardar.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar / imprimir");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");

        jLabel14.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel14.setText("Transporte:");

        labelTrans.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelTrans.setText("jLabel4");

        labelBeca.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelBeca.setText("jLabel4");

        jLabel16.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel16.setText("Descuento/Beca:");

        jLabel18.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel18.setText("Recargo:");

        labelRecargo.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelRecargo.setText("jLabel4");

        jLabel19.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel19.setText("Tipo de Pago:");

        labelTipoPago.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        labelTipoPago.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelBeca, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54))
                            .addComponent(labelTipoPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelGrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelTutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelTelefono))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTipoPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelBeca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelTrans)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelRecargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarPago();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirmarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirmarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirmarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirmarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                confirmarPago dialog = new confirmarPago(new javax.swing.JFrame(), true, usuario, ciclo);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelBeca;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelGrado;
    private javax.swing.JLabel labelMes;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPago;
    private javax.swing.JLabel labelRecargo;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTipoPago;
    private javax.swing.JLabel labelTrans;
    private javax.swing.JLabel labelTutor;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables

    public void getDatos(String datos[], Date fecha, boolean bandera) {
        formato = new SimpleDateFormat("yyyy-MM-dd");
        java.sql.Date ftabla = java.sql.Date.valueOf(formato.format(fecha));
        labelFecha.setText("" + ftabla);
        labelNombre.setText(datos[0]);
        labelNivel.setText(datos[1]);
        labelGrado.setText(datos[2]);
        labelTutor.setText(datos[3]);
        labelTelefono.setText(datos[4]);
        labelPago.setText(datos[9]);
        labelTrans.setText(datos[8]);
        labelMes.setText(datos[6]);
        labelUsuario.setText(datos[7]);
        transporte = Float.parseFloat(datos[8]);
        colegiatura = Float.parseFloat(datos[10]);
        labelRecargo.setText(datos[12]);
        labelTipoPago.setText(datos[13]);
        if (!datos[11].equals("")) {
            labelBeca.setText(datos[11]);
        } else {
            labelBeca.setText("N/A");
        }

        this.bandera = bandera;
    }

    public void guardarPago() {
        String datos[] = new String[11];
        datos[0] = labelNombre.getText();
        datos[1] = labelMes.getText();
        datos[2] = labelUsuario.getText();
        datos[3] = labelFecha.getText();
        datos[4] = labelGrado.getText();
        datos[5] = labelPago.getText();
        datos[6] = String.valueOf(transporte);
        datos[7] = String.valueOf(colegiatura);
        datos[8] = labelBeca.getText();
        datos[9] = labelRecargo.getText();
        datos[10] = labelTipoPago.getText();

        float suma = Float.parseFloat(labelPago.getText().trim()) + transporte + Float.parseFloat(labelRecargo.getText().trim());
        Map variable = new HashMap();
        variable.put("alumno", datos[0]);
        variable.put("cole", Float.parseFloat(labelPago.getText().trim()));
        variable.put("mes", labelMes.getText());
        variable.put("rec", Float.parseFloat(datos[9]));
        variable.put("total", suma);
        variable.put("trans", Float.parseFloat(datos[6]));
        variable.put("tutor", labelTutor.getText().trim());
        variable.put("user", usuario);
        variable.put("tipo_pago", labelTipoPago.getText());
        System.out.println("Total en Suma:" + suma);
        if (bandera == false) {
            if (fun.realizarPago(ciclo, datos)) {
                JOptionPane.showMessageDialog(rootPane, "Pago realizado con exito");
                this.estado = true;
                String ubicacion = System.getProperty("user.dir") + "/report1.jasper";
                reportes(ubicacion, variable);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(rootPane, "Error al guardar los datos");
            }
        } else if (bandera == true) {
            if (fun.realizarAbono(ciclo, datos)) {
                JOptionPane.showMessageDialog(rootPane, "Pago realizado con exito");
                this.estado = true;
                String ubicacion = System.getProperty("user.dir") + "/report1.jasper";
                reportes(ubicacion, variable);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(rootPane, "Error al guardar los datos");
            }
        }
    }

    public boolean estado() {
        return this.estado;
    }

    private void reportes(String ubicacion, Map variable) {
        try {
            System.out.println(ubicacion);
            JasperReport reporte = (JasperReport) JRLoader.loadObjectFromFile(ubicacion);
            JasperPrint imprimir = JasperFillManager.fillReport(reporte, variable, new conexion().getConexion());
            JasperViewer ver = new JasperViewer(imprimir, false);
            ver.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
